architect:
  - zehaoj

merge:
  commanders:
    - zehaoj

  script: |
    ./gradlew test
    echo "easter egg!"

release:
  commanders:
    - zehaoj

  script: |
    ./gradlew test
    git commit -am "${tag}"
